import { withBasePath } from "@/lib/path";

export const company = {
  name: "Flagel Huber Flagel",
  shortName: "FHF",
  tagline: "Building Lifelong Prosperity",
  description:
    "Independent certified public accounting and advisory firm serving families and businesses since 1933. Over 50 employees with 30+ CPAs providing straightforward accounting, tax, and business advice.",
  founded: 1933,
  email: "info@fhf-cpa.com",
  fax: "937-293-5481",
  clientPortal: "https://fhf-cpa.sharefile.com",
  paymentPortal: "https://payerexpress.com/ebp/FHF/",
  social: {
    facebook: "https://www.facebook.com/FlagelHuberFlagel",
    linkedin: "https://www.linkedin.com/company/flagel-huber-flagel",
  },
};

export const offices = [
  {
    id: "cincinnati",
    city: "Cincinnati",
    address: "9135 Governors Way",
    cityStateZip: "Cincinnati, OH 45249",
    phone: "513-774-0300",
    mapLink:
      "https://maps.google.com/?q=9135+Governors+Way+Cincinnati+OH+45249",
  },
  {
    id: "dayton",
    city: "Dayton",
    address: "3400 South Dixie Drive",
    cityStateZip: "Dayton, OH 45439",
    phone: "937-299-3400",
    mapLink:
      "https://maps.google.com/?q=3400+South+Dixie+Drive+Dayton+OH+45439",
  },
  {
    id: "troy",
    city: "Troy",
    address: "1061 South Dorset Road",
    cityStateZip: "Troy, OH 45373",
    phone: "937-339-3118",
    mapLink:
      "https://maps.google.com/?q=1061+South+Dorset+Road+Troy+OH+45373",
  },
];

export const services = [
  {
    id: "tax-services",
    title: "Tax Services",
    shortDescription:
      "Strategic tax planning and compliance for individuals and businesses to minimize liability and ensure compliance.",
    description:
      "Our tax professionals provide comprehensive tax planning and compliance services for individuals, families, and businesses of all sizes. We go beyond simple tax return preparation to identify strategies that minimize your tax burden across multiple years.",
    icon: "FileText",
    iconImg: withBasePath("/images/icons/tax-services.svg"),
    benefits: [
      "Individual & business tax return preparation",
      "Multi-year strategic tax planning",
      "IRS audit representation",
      "State and local tax compliance",
      "Tax-efficient business structuring",
    ],
  },
  {
    id: "assurance-services",
    title: "Assurance Services",
    shortDescription:
      "Independent audits, reviews, and compilations that provide credibility to your financial statements.",
    description:
      "Our assurance professionals deliver audits, reviews, and compilations with objectivity and thoroughness. We serve privately held companies, nonprofits, and employee benefit plans requiring independent financial statement attestation.",
    icon: "ShieldCheck",
    iconImg: withBasePath("/images/icons/assurance.svg"),
    benefits: [
      "Financial statement audits",
      "Review and compilation engagements",
      "Employee benefit plan audits",
      "Nonprofit organization audits",
      "Internal control assessments",
    ],
  },
  {
    id: "small-business-accounting",
    title: "Small Business Accounting",
    shortDescription:
      "Bookkeeping, payroll, and accounting support so you can focus on running your business.",
    description:
      "We serve as an outsourced accounting department for small businesses, handling the day-to-day financial record-keeping so owners can focus on what they do best. From bookkeeping to financial reporting, we provide the infrastructure your business needs.",
    icon: "Calculator",
    iconImg: withBasePath("/images/icons/small-biz-accounting.svg"),
    benefits: [
      "Monthly bookkeeping and reconciliation",
      "Financial statement preparation",
      "Payroll processing and reporting",
      "Cash flow management",
      "QuickBooks setup and training",
    ],
  },
  {
    id: "business-valuations",
    title: "Business Valuations",
    shortDescription:
      "Credentialed valuation services for transactions, disputes, estate planning, and more.",
    description:
      "Our credentialed business valuation specialists (ABV) provide defensible valuations for a wide range of purposes including buy-sell agreements, estate and gift tax planning, shareholder disputes, ESOP transactions, and mergers and acquisitions.",
    icon: "TrendingUp",
    iconImg: withBasePath("/images/icons/business-valuation.svg"),
    benefits: [
      "Buy-sell agreement valuations",
      "Estate and gift tax valuations",
      "ESOP feasibility and valuation",
      "Litigation support valuations",
      "Mergers & acquisitions due diligence",
    ],
  },
  {
    id: "litigation-support",
    title: "Litigation Support",
    shortDescription:
      "Expert witness testimony, forensic accounting, and financial analysis for legal matters.",
    description:
      "Our litigation support team provides forensic accounting, expert witness services, and financial analysis for attorneys and their clients involved in business disputes, divorce proceedings, fraud investigations, and damage calculations.",
    icon: "Scale",
    iconImg: withBasePath("/images/icons/litigation-support.svg"),
    benefits: [
      "Expert witness testimony (CFF credentialed)",
      "Forensic accounting investigations",
      "Lost profits and damages calculations",
      "Business dispute financial analysis",
      "Divorce financial analysis",
    ],
  },
  {
    id: "esop",
    title: "Employee Stock Ownership Plans (ESOP)",
    shortDescription:
      "Comprehensive ESOP services from feasibility through ongoing administration and compliance.",
    description:
      "ESOPs are a powerful business succession and tax planning tool. We guide business owners through every step — from initial feasibility analysis to ESOP formation, annual valuation, and ongoing compliance requirements.",
    icon: "Users",
    iconImg: withBasePath("/images/icons/esop.svg"),
    benefits: [
      "ESOP feasibility studies",
      "Transaction advisory and structuring",
      "Annual ESOP valuations",
      "Department of Labor audit representation",
      "Ongoing trustee and plan advisory",
    ],
  },
  {
    id: "employee-benefit-plan-audits",
    title: "Employee Benefit Plan Audits",
    shortDescription:
      "DOL-compliant audits for 401(k), 403(b), and other qualified retirement plans.",
    description:
      "Retirement plans with 100 or more eligible participants are generally required to have an annual independent audit. Our employee benefit plan audit team has extensive experience with 401(k), 403(b), and profit-sharing plans, ensuring compliance with DOL and ERISA requirements.",
    icon: "ClipboardCheck",
    iconImg: withBasePath("/images/icons/employee-benefits.svg"),
    benefits: [
      "401(k) and 403(b) plan audits",
      "ERISA compliance review",
      "DOL examination support",
      "Plan correction consulting",
      "Form 5500 preparation",
    ],
  },
  {
    id: "business-advisory",
    title: "Business Advisory",
    shortDescription:
      "Strategic guidance on growth, succession, mergers, and profitability from trusted advisors.",
    description:
      "Beyond accounting and tax, our advisors serve as a sounding board and strategic partner for business owners facing key decisions. From buy-sell planning and succession to operational improvement and profit enhancement, we provide the insight that drives better outcomes.",
    icon: "Lightbulb",
    iconImg: withBasePath("/images/icons/business-advisory.svg"),
    benefits: [
      "Business succession planning",
      "Buy-sell agreement structuring",
      "Profit improvement analysis",
      "Cash flow forecasting",
      "Strategic planning facilitation",
    ],
  },
  {
    id: "trust-estate",
    title: "Trust & Estate Tax Planning",
    shortDescription:
      "Preserve wealth across generations with proactive estate and trust tax strategies.",
    description:
      "We work closely with families and their estate planning attorneys to minimize estate and gift taxes, structure trusts efficiently, and ensure fiduciary tax compliance. Our goal is to help you transfer wealth to the next generation in the most tax-efficient manner possible.",
    icon: "Home",
    iconImg: withBasePath("/images/icons/trust-estate.svg"),
    benefits: [
      "Estate and gift tax planning",
      "Fiduciary income tax returns (Form 1041)",
      "Trust administration coordination",
      "Generation-skipping transfer tax planning",
      "Charitable giving strategies",
    ],
  },
];

export const industries = [
  {
    id: "family-closely-held-businesses",
    title: "Family & Closely Held Businesses",
    description:
      "We understand the unique blend of personal and business financial concerns that family businesses face. From succession planning to buy-sell agreements, we help families build and protect their business legacy.",
    icon: "Building2",
    iconImg: withBasePath("/images/icons/family-business.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/family-business-photo-1024x641.jpg",
  },
  {
    id: "real-estate",
    title: "Real Estate",
    description:
      "Real estate investors, developers, and operators benefit from our deep expertise in cost segregation, like-kind exchanges (1031), passive activity rules, and entity structuring to maximize after-tax returns.",
    icon: "Home",
    iconImg: withBasePath("/images/icons/real-estate.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/real-estate-photo-1024x597.jpg",
  },
  {
    id: "manufacturing-distribution",
    title: "Manufacturing & Distribution",
    description:
      "We serve manufacturers and distributors with inventory accounting, cost accounting, R&D tax credits, and the operational insight needed to improve margins and manage growth.",
    icon: "Factory",
    iconImg: withBasePath("/images/icons/manufacturing.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/manufacturing-photo-1024x597.jpg",
  },
  {
    id: "restaurants-retail",
    title: "Restaurants & Retail",
    description:
      "The restaurant and retail industries require careful cash management and sales tax compliance. We provide the financial oversight and planning that helps operators stay profitable and compliant.",
    icon: "ShoppingBag",
    iconImg: withBasePath("/images/icons/restaurants.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/restaurants-photo-1024x597.jpg",
  },
  {
    id: "healthcare-medical-practices",
    title: "Healthcare & Medical Practices",
    description:
      "Physicians, dentists, and healthcare organizations trust us for practice management advisory, entity structuring, retirement plan optimization, and the complex tax issues unique to healthcare.",
    icon: "HeartPulse",
    iconImg: withBasePath("/images/icons/healthcare.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/individual-photo-1024x597.jpg",
  },
  {
    id: "nonprofit-organizations",
    title: "Nonprofit Organizations",
    description:
      "We provide audit, tax (Form 990), and advisory services to nonprofits, helping boards fulfill their fiduciary responsibilities and maintain the public trust essential to mission-driven organizations.",
    icon: "Heart",
    iconImg: withBasePath("/images/icons/non-profit.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/non-profit-photo-1024x597.jpg",
  },
  {
    id: "individuals",
    title: "Individuals & High Net Worth",
    description:
      "From executives and business owners to retirees and investors, we provide personalized tax planning, investment tax strategy, and estate planning coordination for individuals with complex financial lives.",
    icon: "User",
    iconImg: withBasePath("/images/icons/individual.svg"),
    photo: "https://fhf-cpa.com/wp-content/uploads/2021/09/individual-photo-1024x597.jpg",
  },
];

export type TeamMember = {
  name: string;
  credentials: string;
  title: string;
  slug: string;
  photo: string;
  email: string | null;
  phone: string | null;
  linkedin: string | null;
  bio: string;
  specialties: string[];
  education: string[];
  community: string[];
};

export const team: TeamMember[] = [
  {
    name: "Jeff Woeste",
    credentials: "CPA",
    title: "Managing Partner",
    slug: "jeff-woeste",
    photo: withBasePath("/images/team/woeste.webp"),
    email: "jwoeste@fhf-cpa.com",
    phone: "937-528-7212",
    linkedin: "https://www.linkedin.com/in/jeffwoeste/",
    bio: "Jeff has been with the firm for over 20 years, specializing in small business tax with an emphasis on family-owned service businesses, medical practices, and real estate. He emphasizes a relational approach — getting to know the current generation of business owners, the next generation, and sometimes the third. He describes the CPA's advisor role similarly to that of a quarterback: coordinating all the right specialists on behalf of the client. \"The single most attractive aspect to me about FHF is the fact that there are so many 'lifers' here — folks that started as interns and have stayed at FHF since.\" Outside work, Jeff enjoys golf and spending time with his wife Laura and three children.",
    specialties: ["Tax Services", "Family & Closely Held Businesses", "Healthcare & Medical Practices", "Real Estate"],
    education: ["Wright State University — B.S. in Management Information Systems, Accountancy"],
    community: ["Dayton Art Institute & Oktoberfest", "Rotary"],
  },
  {
    name: "Kevin Behrle",
    credentials: "CPA",
    title: "Partner",
    slug: "kevin-behrle",
    photo: withBasePath("/images/team/behrle.jpg"),
    email: "kbehrle@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/kevinbehrle/",
    bio: "\"Initially, I chose Flagel Huber Flagel because of the people and down-to-earth atmosphere of the firm. The opportunity to choose the areas in which I would practice was offered to me on day one.\" Kevin stayed with the firm because he saw the value FHF provides to clients, wanting to make an impact on small and medium-sized private businesses and individuals. \"The diversity of our client base, the experience of our professionals, and our external resources allow us to address the diverse needs that may arise.\"",
    specialties: ["Family & Closely Held Businesses", "Tax Services"],
    education: ["Purdue University — B.S. in Management, Accounting"],
    community: [],
  },
  {
    name: "Dave Dirksen",
    credentials: "CPA/ABV",
    title: "Partner",
    slug: "dave-dirksen",
    photo: withBasePath("/images/team/dirksen.jpg"),
    email: "ddirksen@fhf-cpa.com",
    phone: "937-299-3400",
    linkedin: "https://www.linkedin.com/in/davedirksen/",
    bio: "Dave brings over 30 years of experience at Flagel Huber Flagel, with a foundational belief that relationships matter. He describes himself as a mentor, leader, partner, and supporter of his firm colleagues. \"I thoroughly enjoy the camaraderie and relationships that I have established with my clients and co-workers.\" Dave leverages extensive technical expertise in real estate, family businesses, manufacturing, and high-net-worth taxation. He finds particular reward in assisting with family business transitions between generations. Personally, Dave enjoys music, boating, golfing, and time with family.",
    specialties: ["Real Estate", "Family & Closely Held Businesses", "Manufacturing & Distribution", "Employee Stock Ownership Plans"],
    education: ["Wright State University — B.S. in Business, Accounting & Finance"],
    community: ["Dor-wood Optimist Club — active member, past multi-year Treasurer"],
  },
  {
    name: "Sean Costello",
    credentials: "",
    title: "IT Director",
    slug: "sean-costello",
    photo: withBasePath("/images/team/costello.jpg"),
    email: "scostello@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/sean-costello-87464080/",
    bio: "Sean Costello joined Flagel Huber Flagel in 2015 as IT Manager and has since become the firm's IT Director. With twenty-five years of IT experience from a Dayton area law firm and computer company, Sean is a problem solver who enjoys making FHF run smoothly by addressing IT challenges before they arise. \"I think people in IT have a stigma that we work out of a dark closet and aren't approachable. I wanted to change that and be easy to approach and make IT friendly for everyone.\" Sean values FHF's comfortable family atmosphere and how everyone genuinely cares about the firm's and clients' well-being. Outside work, he enjoys golfing and camping.",
    specialties: ["Information Technology", "IT Infrastructure & Security"],
    education: ["New Horizons Computer Learning Center"],
    community: [],
  },
  {
    name: "Matt Deitsch",
    credentials: "CPA",
    title: "Partner",
    slug: "matt-deitsch",
    photo: withBasePath("/images/team/deitsch.jpg"),
    email: "mdeitsch@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/matt-deitsch-3594608/",
    bio: "\"I took a position with Flagel Huber Flagel because I was intrigued by the value that was placed on family and maintaining a positive work/life balance. I really enjoy the culture of the firm and the size and types of clients that FHF serves. I especially enjoy interacting with the large number of family-owned, small and medium-sized businesses. The people at FHF really care about each other and our clients. Though I am based in our Cincinnati office, I frequently work in our Dayton office. This provides me with the opportunity to regularly interact with co-workers in both offices and visit with a wide range of clients.\"",
    specialties: ["Family & Closely Held Businesses", "Tax Services"],
    education: [
      "Miami University — B.S. in Business, Accountancy & Finance",
      "Miami University — Master of Accountancy",
    ],
    community: [],
  },
  {
    name: "Liz Downer",
    credentials: "CPA, CFP®",
    title: "Partner",
    slug: "liz-downer",
    photo: withBasePath("/images/team/downer.webp"),
    email: "edowner@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/elizabethdowner/",
    bio: "Originally from Cincinnati, Liz joined the firm in 2016 and now proudly calls Dayton home. She focuses on tax consulting, planning, and compliance for family and closely held businesses as well as individuals. Her expertise extends to complex trust and estate matters, including the challenges of generational wealth transfer and the tax considerations associated with estate planning. Driven by a commitment to providing the highest quality service, Liz considers it a privilege to add value to her clients' lives each day. Liz is married with two children. Outside of work, she enjoys traveling, hiking, bicycling, making memories with friends and family, and checking out new restaurants around town.",
    specialties: ["Tax Services", "Family & Closely Held Businesses", "Trust & Estate Tax Planning"],
    education: ["The Ohio State University — B.S. in Business Administration, Accountancy"],
    community: [],
  },
  {
    name: "Joe Gordon",
    credentials: "CPA",
    title: "Partner",
    slug: "joe-gordon",
    photo: withBasePath("/images/team/gordon.jpg"),
    email: "jgordon@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/josephmgordon/",
    bio: "Joe Gordon has spent his 34-year public accounting career at Flagel Huber Flagel. He leverages multifaceted knowledge across a wide range of disciplines to make an impact in his clients' lives and businesses. \"Knowing that I can guide businesses through some of their challenges and be a part of their success is really gratifying to me. At the end of the day, when their business is successful, everyone is successful.\" Joe has developed deep expertise in Manufacturing and Distribution, Healthcare and Medical, and Real Estate industries. He values FHF's family feel and how the entire team is committed to building relationships and passionately serving clients.",
    specialties: ["Employee Benefit Plan Audits", "Small Business Accounting", "Assurance Services", "Tax Services", "Manufacturing & Distribution", "Healthcare & Medical Practices", "Real Estate"],
    education: ["Wright State University — B.S. in Business, Accountancy"],
    community: ["Youth sports coach", "Athletic Association treasurer", "Church finance committee", "Local non-profit volunteer"],
  },
  {
    name: "Kevin Hagstrom",
    credentials: "CPA",
    title: "Partner",
    slug: "kevin-hagstrom",
    photo: withBasePath("/images/team/hagstrom.jpg"),
    email: "khagstrom@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/kevinhagstrom/",
    bio: "Kevin Hagstrom has spent his entire 21-year tax and accounting career at Flagel Huber Flagel, starting as a summer intern in 1999 and officially joining in 2000 as a Staff Accountant. He has worked his way up to Partner. Kevin enjoys being a trusted advisor to his clients, helping Family & Closely Held Businesses and Nonprofit organizations with a variety of tax and assurance services. \"It is rewarding, in many ways, to work alongside my clients. Whether the work is performing an audit, preparing tax returns or some other unique project, I find satisfaction in knowing I can use my knowledge and skills in their businesses or personal endeavors.\" He is also committed to mentorship and employee development.",
    specialties: ["Nonprofit Organizations", "Tax Services", "Assurance Services", "Family & Closely Held Businesses"],
    education: [
      "Wright State University — B.S. in Business",
      "Wright State University — Master of Accountancy",
    ],
    community: ["Kettering Centerville Kiwanis Club", "Church volunteer", "Youth sports coach"],
  },
  {
    name: "Matt Jones",
    credentials: "CPA",
    title: "Partner",
    slug: "matt-jones",
    photo: withBasePath("/images/team/jones.jpg"),
    email: "mjones@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/mattrjonescpa/",
    bio: "\"I most enjoy the long-term relationships we build with our clients. Getting to know our clients and their businesses so well helps us to add even more value to their decision making. I want clients to feel like family.\" Matt joined the firm in 2006 and focuses on family and closely held businesses, especially construction and manufacturing. He provides audits, bookkeeping, business tax, and personal tax preparation and planning. Matt lives north of Dayton in Arcanum with his wife Ashley and two children, and volunteers with several local boards and organizations. He enjoys golf and visiting renowned courses.",
    specialties: ["Family & Closely Held Businesses", "Individuals", "Manufacturing & Distribution", "Tax Services", "Employee Benefit Plan Audits", "Nonprofit Organizations"],
    education: [
      "Wright State University — B.S. in Accounting",
      "Wright State University — Master of Accountancy",
    ],
    community: ["Board Member, Film Dayton", "Planned Giving Advisory Council, Dayton Children's Hospital", "Arcanum Lions Club"],
  },
  {
    name: "Derek Koester",
    credentials: "CPA",
    title: "Partner",
    slug: "derek-koester",
    photo: withBasePath("/images/team/koester.jpg"),
    email: "DKoester@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/derek-koester-cpa-73138141/",
    bio: "Derek joined the FHF team when Nolan Giere & Company and FHF merged in 2021, having spent eight years serving Nolan Giere clients. He joined as a staff accountant in summer 2013, earned his CPA certification in March 2016, was promoted to supervisor in 2016 and manager in 2019. Derek works in tax planning, financial statement preparation, personal and corporate tax preparation, and consulting services. \"I'm looking forward to providing our clients with additional tax and accounting services that we didn't previously offer as Nolan Giere & Company.\" Derek enjoys spending time with his three daughters and wife in their camper.",
    specialties: ["Tax Services", "Family & Closely Held Businesses", "Manufacturing & Distribution"],
    education: [
      "Wright State University — B.S. in Accounting",
      "Wright State University — Master of Accountancy",
    ],
    community: ["Ohio Society of CPAs", "AICPA", "Troy Rotary Club", "2016 Leadership Troy Graduate", "Treasurer, Isaiah's Place"],
  },
  {
    name: "Bruce Kreinbrink",
    credentials: "CPA, CFP®",
    title: "Partner",
    slug: "bruce-kreinbrink",
    photo: withBasePath("/images/team/kreinbrink.jpg"),
    email: "bkreinbrink@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/brucekreinbrink/",
    bio: "Bruce has served the firm for over 30 years, providing guidance to business and individual clients. He leads the Family & Closely Held Business Team, assisting owners with tax planning, compliance, and accounting outsourcing. His expertise extends to estate and trust matters, including ownership transfers and tax-minimizing estate planning strategies. Bruce earned his degree from Wright State University while playing collegiate baseball. Outside of work, he enjoys baseball, spending time with family, and watching cooking competition shows.",
    specialties: ["Family & Closely Held Businesses", "Business Advisory", "Trust & Estate Tax Planning", "Tax Services"],
    education: ["Wright State University — B.S. in Business"],
    community: ["Prior President, Prevent Blindness — Dayton Chapter"],
  },
  {
    name: "Randy Kuvin",
    credentials: "CPA/ABV, CFF",
    title: "Partner",
    slug: "randy-kuvin",
    photo: withBasePath("/images/team/kuvin.jpg"),
    email: "rkuvin@fhf-cpa.com",
    phone: "937-299-3400",
    linkedin: "https://www.linkedin.com/in/randykuvin/",
    bio: "Randy has worked at Flagel Huber Flagel for nearly 40 years, focusing on helping clients build and preserve wealth. He specializes in business valuation, litigation support, and real estate accounting. His expertise includes determining business values for divorce proceedings and providing forensic analysis for income and contract matters. Randy served as Managing Partner from 2008–2022, navigating the firm through the Great Recession, COVID-19 pandemic, and two strategic mergers. Beyond his professional role, Randy volunteers extensively with community organizations, serves in his church music ministry, and has completed four marathons.",
    specialties: ["Business Valuations", "Litigation Support", "Real Estate", "Tax Services"],
    education: ["Miami University — B.S. in Business, Accountancy"],
    community: ["Mason Deerfield Chamber of Commerce", "St. Margaret of York choir and cantor", "Warren County Small Business Development Alliance", "Working In Neighborhoods, Inc.", "SMAC Running Club"],
  },
  {
    name: "Chris McCaskey",
    credentials: "CPA",
    title: "Partner",
    slug: "chris-mccaskey",
    photo: withBasePath("/images/team/mccaskey.webp"),
    email: "cmccaskey@fhf-cpa.com",
    phone: "937-528-7244",
    linkedin: "https://www.linkedin.com/in/chrismccaskey/",
    bio: "Chris began his career at FHF in 1997 as a Staff Accountant after graduating from Cedarville College. After leaving to pursue other accounting and controller opportunities, he returned to FHF as a Manager in 2012 and is now a Partner. Chris serves family and privately held businesses, nonprofit organizations, and individuals with their tax and accounting needs. \"As a partner at FHF, I get to be a part of a team of 'good business people;' we help build our clients' businesses, serve as role models and contribute to the community.\" He makes it a priority to make an impact in his local community.",
    specialties: ["Family & Closely Held Businesses", "Nonprofit Organizations", "Individuals", "Tax Services"],
    education: ["Cedarville College — B.S. in Accounting"],
    community: ["Treasurer, Legacy Christian Academy", "Board of Directors, American Red Cross Dayton Area Chapter", "Board of Directors, Dayton Society of Natural History", "AICPA member", "OSCPA member"],
  },
  {
    name: "Mike Pabst",
    credentials: "CPA",
    title: "Partner",
    slug: "mike-pabst",
    photo: withBasePath("/images/team/pabst.jpg"),
    email: "mpabst@fhf-cpa.com",
    phone: "937-528-7223",
    linkedin: "https://www.linkedin.com/in/mikepabst/",
    bio: "\"I chose Flagel Huber Flagel because they inspire leadership, encourage community involvement, and stimulate knowledge and continuous education. I believe this environment builds success and confidence, which translates into strong client relationships. It's these qualities that guide our mission of helping our clients build and preserve wealth.\"",
    specialties: ["Family & Closely Held Businesses", "Manufacturing & Distribution", "Tax Services"],
    education: ["Wright State University — B.S. in Accounting and Finance"],
    community: [],
  },
  {
    name: "Brett Vandeman",
    credentials: "CPA",
    title: "Partner",
    slug: "brett-vandeman",
    photo: withBasePath("/images/team/vandeman.jpg"),
    email: "bvandeman@fhf-cpa.com",
    phone: "937-528-7247",
    linkedin: "https://www.linkedin.com/in/brettvandeman/",
    bio: "Brett Vandeman has been with FHF for over ten years and leads the firm's team serving Manufacturing, Distribution, Wholesale, and Construction sectors. He holds Bachelor's and Master's degrees in Accountancy from Wright State University and served as an adjunct professor of accountancy at the University of Dayton. Brett applies his business acumen and client-centric approach to help clients navigate their situations. \"I support and identify with the company's mission, and their values are my values. I enjoy helping individuals and businesses achieve success.\" Personally, Brett is married with two children and enjoys sports, football, baseball, and golf.",
    specialties: ["Manufacturing & Distribution", "Employee Benefit Plan Audits", "Tax Services", "Assurance Services"],
    education: [
      "Wright State University — B.S. in Accountancy",
      "Wright State University — Master of Accountancy",
    ],
    community: ["Board Member, Learning Tree Farm"],
  },
  {
    name: "Amy Bales",
    credentials: "",
    title: "Human Resources",
    slug: "amy-bales",
    photo: withBasePath("/images/team/bales.jpg"),
    email: null,
    phone: null,
    linkedin: null,
    bio: "Amy is a member of the Flagel Huber Flagel team, supporting the firm's human resources operations across all three offices.",
    specialties: ["Human Resources"],
    education: [],
    community: [],
  },
  {
    name: "Luke Berning",
    credentials: "CPA",
    title: "Supervisor",
    slug: "luke-berning",
    photo: withBasePath("/images/team/berning.jpg"),
    email: "lberning@fhf-cpa.com",
    phone: null,
    linkedin: null,
    bio: "Luke Berning started with FHF in January 2020 as an intern and quickly recognized the firm as a special place. After completing his Bachelor of Business Administration in Accounting, he joined as a staff accountant. After departing to explore other paths, Luke rejoined the firm in May 2024 as a supervisor. He specializes in assurance and audit services across multiple sectors.",
    specialties: ["Assurance Services", "Real Estate", "Healthcare", "Golf Courses & Country Clubs", "Staffing"],
    education: ["University of Cincinnati — B.B.A. in Accounting"],
    community: [],
  },
  {
    name: "Andee Everman",
    credentials: "",
    title: "Manager",
    slug: "andee-everman",
    photo: withBasePath("/images/team/everman.jpg"),
    email: "aeverman@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/andee-everman/",
    bio: "Andee is a Manager at Flagel Huber Flagel, bringing organizational expertise and a commitment to client service to the firm's operations.",
    specialties: ["Business Operations", "Client Services"],
    education: ["The Ohio State University"],
    community: ["VP of Communications, Junior League of Dayton"],
  },
  {
    name: "John O'Brien",
    credentials: "CPA",
    title: "Manager",
    slug: "john-obrien",
    photo: withBasePath("/images/team/obrien.webp"),
    email: null,
    phone: null,
    linkedin: "https://www.linkedin.com/in/john-o-brien-cpa/",
    bio: "\"I enjoy working at FHF because of the people. This includes both my co-workers and the clients we work with. There is a strong culture here of bright people that are focused on delivering quality work and employee growth and improvement. I also enjoy being able to work on a large range of accounting services whether it is tax planning, business and individual tax preparation, financial statement preparation, or consulting services.\"",
    specialties: ["Tax Planning", "Business & Individual Tax Preparation", "Financial Statement Preparation", "Consulting Services"],
    education: [
      "Miami University — B.S. in Accounting",
      "Miami University — Master of Accountancy",
    ],
    community: [],
  },
  {
    name: "Erin Kliesch",
    credentials: "CPA",
    title: "Manager",
    slug: "erin-kliesch",
    photo: withBasePath("/images/team/kliesch.jpg"),
    email: "ekliesch@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/erinkliesch/",
    bio: "\"Flagel is a family-oriented environment that prides itself on integrity, compassion and quality service. We work as a team to resolve issues and work on improvements with clients so they can be successful.\" Erin concentrates most of her time on managing audits, primarily serving not-for-profit organizations, employee benefit plans, and low-income housing tax credit projects. \"I am committed to quality and value-added services while working together with clients as a team.\"",
    specialties: ["Employee Benefit Plan Audits", "Nonprofit Organizations", "Low-Income Housing Tax Credit Projects", "Assurance Services"],
    education: ["Wright State University — B.S. in Business, Accountancy & Finance"],
    community: [],
  },
  {
    name: "Jenny Lee",
    credentials: "CPA",
    title: "Manager",
    slug: "jenny-lee",
    photo: withBasePath("/images/team/lee.jpg"),
    email: "JLee@fhf-cpa.com",
    phone: null,
    linkedin: "https://www.linkedin.com/in/jenny-lee-cpa-34792a52/",
    bio: "\"Flagel provides valuable and meaningful services to an expansive range of clients every day. At Flagel, I work with clients that are large businesses, family & closely held businesses, healthcare practices, and individuals to provide a full range of tax services including tax planning, tax consulting, tax research, and tax compliance. I truly value the relationships with our clients and the opportunities to serve them in so many ways.\" Jenny also values FHF's focus on work-life balance and the caliber of colleagues she works alongside.",
    specialties: ["Tax Services", "Manufacturing & Distribution", "Healthcare & Medical Practices", "Family & Closely Held Businesses", "Individuals"],
    education: ["University of Maryland — B.S. in Accounting and Supply Chain Management"],
    community: [],
  },
  {
    name: "Randy Miller",
    credentials: "CPA",
    title: "Manager",
    slug: "randy-miller",
    photo: withBasePath("/images/team/miller.jpg"),
    email: "rmiller@fhf-cpa.com",
    phone: null,
    linkedin: null,
    bio: "\"Coming from a family with several small businesses, FHF really aligned with my values of building and supporting our local community. When I started at FHF, it quickly became evident how much my co-workers truly cared about their clients and how our services impact them. I continue to choose FHF for the valuable work we do to enable our clients to achieve their goals. Working at FHF allows me to fulfill my passion for helping people while also continuing to develop professionally.\"",
    specialties: ["Tax Services", "Small Business Accounting", "Family & Closely Held Businesses"],
    education: [
      "Clark State Community College — A.S. in Business",
      "Wright State University — B.S. in Accounting and Finance",
      "Wright State University — Master of Accountancy",
    ],
    community: [],
  },
  {
    name: "Mike Owsiany",
    credentials: "CPA",
    title: "Manager",
    slug: "mike-owsiany",
    photo: withBasePath("/images/team/owsiany.jpg"),
    email: "MOwsiany@fhf-cpa.com",
    phone: "937-528-7234",
    linkedin: "https://www.linkedin.com/in/michael-owsiany-cpa-1a805263/",
    bio: "\"I enjoy working at FHF because the firm values employee growth, which I believe leads to success with clients. FHF supports employees with opportunities to learn, grow and choose the type of work and/or industry that most interests them. This translates to a quality product for clients. There is also an emphasis on work-life balance that allows employees to stay involved and available in their personal lives. These factors help foster a positive work environment, and in turn, deliver lifelong prosperity for clients.\"",
    specialties: ["Employee Benefit Plan Audits", "Manufacturing & Distribution", "Tax Services"],
    education: ["University of Dayton — B.S. in Accountancy (2016)"],
    community: [],
  },
  {
    name: "Katie Pavy",
    credentials: "CPA, M.ACC.",
    title: "Manager",
    slug: "katie-pavy",
    photo: withBasePath("/images/team/pavy.jpg"),
    email: "kpavy@fhf-cpa.com",
    phone: "937-528-7238",
    linkedin: "https://www.linkedin.com/in/katiepavy/",
    bio: "\"Throughout my career, FHF has demonstrated its commitment to employee value by including opportunities for families to meet and socialize; setting the example of putting family first when possible, and providing a flexible work environment for working parents. I continue to choose to work for FHF for this reason, and because of my great co-workers and wonderful clients. I have established relationships with both that have enhanced my career and life experience. FHF fosters a welcoming and friendly environment for its employees which translates into dedicated people who care about their clients and their work.\"",
    specialties: ["Nonprofit Organizations", "Tax Services", "Assurance Services"],
    education: [
      "Wright State University — B.S. in Business",
      "Wright State University — Master of Accountancy",
    ],
    community: [],
  },
];

export const testimonials = [
  {
    quote:
      "FHF have consistently provided outstanding audit service for many years. The continuity of their staff assigned to our engagement has been extremely beneficial.",
    author: "Neal Pemberton",
    source: "Google Reviews",
  },
  {
    quote:
      "The team at FHF goes above and beyond to ensure we understand our financials. Their guidance has been invaluable to our business growth.",
    author: "Local Business Owner",
    source: "Client",
  },
];

export const navLinks = [
  {
    label: "Who We Serve",
    href: "/who-we-serve",
    children: industries.map((i) => ({
      label: i.title,
      href: `/who-we-serve/${i.id}`,
    })),
  },
  {
    label: "What We Do",
    href: "/what-we-do",
    children: services.map((s) => ({
      label: s.title,
      href: `/what-we-do/${s.id}`,
    })),
  },
  {
    label: "Who We Are",
    href: "/who-we-are",
    children: [
      { label: "Our Commitment", href: "/our-commitment" },
      { label: "Our History", href: "/our-history" },
      { label: "Our Team", href: "/team" },
      { label: "Our Locations", href: "/locations" },
      { label: "BDO Alliance USA", href: "/bdo-alliance" },
    ],
  },
  {
    label: "Resources",
    href: "/resources",
    children: [
      { label: "News & Insights", href: "/news" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "Tax Calendar", href: "/resources#tax-calendar" },
      { label: "Financial Tools", href: "/resources#tools" },
      { label: "Careers", href: "/careers" },
    ],
  },
  {
    label: "Contact",
    href: "/contact",
  },
];
